[package]
name = "create-genesis"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
json = "0.11.13"
serde_json = "1.0.39"
ethabi = "7.0.0"
ethereum-types = "0.5.2"
hex = "0.3"
tiny-keccak = "1.4.2"
libsecp256k1 = "0.2.2"
clap = "2.33.0"

libproto = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }

core-executor = { path="../../cita-executor/core", default-features = false}
evm = { path="../../cita-executor/evm"}
