[package]
name = "create_key_addr"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
cita-crypto = { git = "https://github.com/cryptape/cita-common.git", branch = "v0.21.1" }
hashable = { git = "https://github.com/cryptape/cita-common.git", branch = "v0.21.1" }

[features]
default = ["secp256k1", "sha3hash"]
secp256k1 = ["cita-crypto/secp256k1"]
ed25519 = ["cita-crypto/ed25519"]
sm2 = ["cita-crypto/sm2"]
sha3hash = ["hashable/sha3hash"]
blake2bhash = ["hashable/blake2bhash"]
sm3hash = ["hashable/sm3hash"]
