[workspace]
members = ["devtools"
,"jsonrpc"
,"chain"
,"chain/core"
,"chain/types"
,"consensus/tdmint"
,"consensus/txpool"
,"consensus/raft"
,"consensus/authority_round"
,"network"
,"tests/trans_evm"
,"tests/chain_performance"
,"tests/amqp"
,"tests/latency"
]


