[package]
name = "cita-secp256k1"
version = "0.6.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]

[dependencies]
eth-secp256k1 = { git = "https://github.com/paritytech/rust-secp256k1", rev = "6370d63adf4e8c91e2eae9225eef4b4e0294c5d0" }
lazy_static = "0.2"
rustc-serialize = "0.3"
util = {path = "../../share_libs/util"}
rlp = { path = "../rlp" }
rand = "0.3"
serde = "1.0"
serde_json = "1.0"
bincode = "0.8"
