name="cita-monitor"
command = "cita-monitor"
pidfile = ".cita-monitor.pid"

[[process]]
name = "cita-auth"
command = "cita-auth"
args = ["-c","auth.json"]
pidfile = ".cita-auth.pid"
respawn = 3

[[process]]
name = "cita-network"
command = "cita-network"
args = ["-c","network.toml"]
pidfile = ".cita-network.pid"
respawn = 3

[[process]]
name = "cita-tendermint"
command = "cita-tendermint"
args = ["-c","consensus.json"]
pidfile = ".cita-tendermint.pid"
respawn = 3

[[process]]
name = "cita-jsonrpc"
command = "cita-jsonrpc"
args = ["-c","jsonrpc.json"]
pidfile = ".cita-jsonrpc.pid"
respawn = 3


[[process]]
name = "cita-chain"
command = "cita-chain"
args = ["-g","genesis.json","-c","chain.json"]
pidfile = ".cita-chain.pid"
respawn = 3
