[package]
name = "monitor"
version = "0.1.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]

[dependencies]
toml = "0.2"
rustc-serialize = "0.3"
log = "0.3"
clap = "2"
logger = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
util = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }

[features]
default = ["sha3hash"]
sha3hash = ["util/sha3hash"]
blake2bhash = ["util/blake2bhash"]
sm3hash = ["util/sm3hash"]
