[package]
name = "cita-relayer-parser"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
logger = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
cita-types = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
clap = "2"
parking_lot = "0.6"
futures = "0.1"
tokio-core = "0.1"
hyper = { git = "https://github.com/cryptape/hyper.git", branch = "reuse_port" }
core = { path = "../../cita-chain/core" }
jsonrpc-types = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
libproto = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
cita-crypto = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
ethabi = "4.2.0"

[features]
default = ["secp256k1", "sha3hash"]
secp256k1 = ["cita-crypto/secp256k1", "libproto/secp256k1", "jsonrpc-types/secp256k1"]
ed25519 = ["cita-crypto/ed25519", "libproto/ed25519", "jsonrpc-types/ed25519"]
sm2 = ["cita-crypto/sm2", "libproto/sm2", "jsonrpc-types/sm2"]
sha3hash = ["libproto/sha3hash", "jsonrpc-types/sha3hash"]
blake2bhash = ["libproto/blake2bhash", "jsonrpc-types/blake2bhash"]
sm3hash = ["libproto/sm3hash", "jsonrpc-types/sm3hash"]
