[package]
name = "util"
version = "0.6.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]
build = "build.rs"

[dependencies]
blake2b = { path = "../blake2b", optional = true }
sm3 = { path = "../sm3", optional = true }
log = "0.3"
rustc-hex = "1.0"
rand = "0.3.12"
time = "0.1.34"
rocksdb = { git = "https://github.com/paritytech/rust-rocksdb", rev = "4364caec4dd5da1a1d78c39276774ee65bf55c7d" }
elastic-array = "0.9"
rlp = { path = "../rlp" }
heapsize = "0.4"
itertools = "0.5"
sha3 = { path = "../sha3"}
clippy = {version = "0.0.148", optional = true}
libc = "0.2.7"
vergen = "0.1"
target_info = "0.1"
bigint = { path = "../bigint", features = ["heapsizeof"] }
parking_lot = "0.4"
ansi_term = "0.9"
tiny-keccak= "1.0"
ethcore-bloom-journal = { path = "../bloom" }
regex = "0.2"
lru-cache = "0.1.0"
logger = { git = "https://github.com/cryptape/cita-sharelibs.git", rev = "056d5bd" }
uuid = { version = "0.4", features = ["v4"] }

[features]
default = ["sha3hash"]
sha3hash = []
blake2bhash = ["blake2b"]
sm3hash = ["sm3"]

[build-dependencies]
vergen = "*"
rustc_version = "0.1.0"

[dev-dependencies]
mktemp = "0.3.1"
