[package]
name = "util"
version = "0.6.0"
authors = ["zhangsoledad <787953403@qq.com>"]
build = "build.rs"

[dependencies]
blake2b = { path = "../blake2b", optional = true }
sm3 = { path = "../sm3", optional = true }
log = "0.3"
env_logger = "0.4"
rustc-hex = "1.0"
rand = "0.3.12"
time = "0.1.34"
rocksdb = { git = "https://github.com/paritytech/rust-rocksdb" }
elastic-array = "0.9"
rlp = { path = "../rlp" }
heapsize = "0.4"
itertools = "0.5"
sha3 = { path = "../sha3", optional = true }
clippy = { version = "0.0.103", optional = true }
devtools = { path = "../../devtools" }
libc = "0.2.7"
vergen = "0.1"
target_info = "0.1"
bigint = { path = "../bigint", features = ["heapsizeof"] }
parking_lot = "0.4"
ansi_term = "0.9"
tiny-keccak= "1.0"
ethcore-bloom-journal = { path = "../bloom" }
regex = "0.2"
lru-cache = "0.1.0"
ethcore-logger = { path = "../logger" }
uuid = { version = "0.4", features = ["v4"] }

[features]
default = ["sha3hash"]
sha3hash = ["sha3"]
blake2bhash = ["blake2b"]
sm3hash = ["sm3"]

[build-dependencies]
vergen = "*"
rustc_version = "0.1.0"
