[package]
name = "cita-network"
version = "0.6.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
clap = "2"
serde = "1.0"
serde_derive = "1.0"
futures = "0.1"
byteorder = "1.0.0"
dotenv = "0.13.0"
bytes = "0.4"
notify = "4.0.0"
libproto = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
util = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
pubsub = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
logger = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
rand = "0.3.*"
tokio = "0.1.8"

[dev-dependencies]
tempfile = "2"

[build-dependencies]
util = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }


[features]
default = ["secp256k1", "sha3hash", "rabbitmq"]
secp256k1 = ["libproto/secp256k1"]
ed25519 = ["libproto/ed25519"]
sm2 = ["libproto/sm2"]
sha3hash = ["util/sha3hash", "libproto/sha3hash"]
blake2bhash = ["util/blake2bhash", "libproto/blake2bhash"]
sm3hash = ["util/sm3hash", "libproto/sm3hash"]
rabbitmq = ["pubsub/rabbitmq"]
zeromq = ["pubsub/zeromq"]
kafka = ["pubsub/kafka"]
