[package]
description = "CITA node."
name = "chain"
version = "0.6.0"
authors = []

[dependencies]
dotenv = "0.10.0"
threadpool = "1.3.2"
protobuf = { version = "^1.0.0"}
log = "0.3.0"
clap = "2"
byteorder = { version = "1", default-features = false }
serde_json = "1.0"
libproto = {path = "../share_libs/proto"}
pubsub = { path = "../share_libs/pubsub" }
util = { path = "../share_libs/util" }
logger = { path = "../share_libs/logger" }
jsonrpc_types = { path = "../jsonrpc/types" }
core = { path = "./core" }
common-types = { path = "./types" }


[[bin]]
path = "main.rs"
name = "chain"

